window.$ = window.jQuery = require('jquery')
require('popper.js')
require('bootstrap')
require('jquery.nicescroll')
require('moment')
require('summernote')
require('datatables')
require('datatables.net-responsive-bs4')